nodes:
  - address: 172.31.17.98
    port: 22
    internal_address: ""
    role:
    - controlplane
    - etcd
    hostname_override: ""
    docker_socket: /var/run/docker.sock
    user: centos
    ssh_agent_auth: true
    ssh_key_path: /home/centos/.ssh/tjrohweder.pem
    ssh_cert: ""
    ssh_cert_path: ""
    labels: {}
    taints: []
  - address: 172.31.30.199
    port: 22
    internal_address: ""
    role:
    - controlplane
    - etcd
    hostname_override: ""
    docker_socket: /var/run/docker.sock
    user: centos
    ssh_agent_auth: true
    ssh_key_path: /home/centos/.ssh/tjrohweder.pem
    ssh_cert: ""
    ssh_cert_path: ""
    labels: {}
    taints: []
  - address: 172.31.29.206
    port: 22
    internal_address: ""
    role:
    - controlplane
    - etcd
    hostname_override: ""
    docker_socket: /var/run/docker.sock
    user: centos
    ssh_agent_auth: true
    ssh_key_path: /home/centos/.ssh/tjrohweder.pem
    ssh_cert: ""
    ssh_cert_path: ""
    labels: {}
    taints: []
  - address: 172.31.22.121
    port: 22
    internal_address: ""
    role:
    - worker
    hostname_override: ""
    docker_socket: /var/run/docker.sock
    user: centos
    ssh_key: ""
    ssh_key_path: /home/centos/.ssh/tjrohweder.pem
    ssh_agent_auth: true
    ssh_cert: ""
    ssh_cert_path: ""
    taints: []
  - address: 172.31.17.80
    port: 22
    internal_address: ""
    role:
    - worker
    hostname_override: ""
    docker_socket: /var/run/docker.sock
    user: centos
    ssh_key: ""
    ssh_key_path: /home/centos/.ssh/tjrohweder.pem
    ssh_agent_auth: true
    ssh_cert: ""
    ssh_cert_path: ""
    taints: []
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    backup_config:
      interval_hours: 12
      retention: 6
    snapshot: true
    creation: 6h
    retention: 24h
  kube-api:
    image: ""
    extra_args:
      v: 10
      default-not-ready-toleration-seconds: 10
      default-unreachable-toleration-seconds: 10
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: "30000-32767"
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config:
      enabled: true
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    extra_args:
      pod-eviction-timeout: 30s
      node-monitor-grace-period: 20s
      horizontal-pod-autoscaler-downscale-delay: "10m0s"
      horizontal-pod-autoscaler-upscale-delay: "5m0s"
      horizontal-pod-autoscaler-sync-period: "5s"
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
  kubelet:
    image: ""
    extra_args:
      read-only-port: 10255
      node-status-update-frequency: 2s
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
network:
  plugin: calico
  options: {}
  mtu: 0
  node_selector: {}
  update_strategy: null
authentication:
  strategy: x509
  sans: []
  webhook: null
addons: ""
addons_include: []
kubernetes_version: v1.20.9-rancher1-1
ssh_key_path: ~/.ssh/id_rsa
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: null
private_registries: []
ingress:
  provider: nginx
  options:
     use-forwarded-headers: "true"
     proxy-body-size: "0"
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
  update_strategy: null
cluster_name: "rke"
prefix_path: ""
win_prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
monitoring:
  provider: ""
  options: {}
  node_selector: {}
  update_strategy: null
  replicas: null
restore:
  restore: false
  snapshot_name: ""
dns:
  provider: coredns