---

kind: Namespace
apiVersion: v1
metadata:
  name: istio-system
  labels:
    name: istio-system
---

kind: Namespace
apiVersion: v1
metadata:
  name: longhorn-system
  labels:
    name: longhorn-system
---

kind: Namespace
apiVersion: v1
metadata:
  name: metallb
  labels:
    name: metallb
