---
- hosts: masters[0]
  remote_user: "centos"
  tasks:
    - name: Add Longhorn helm repository
      shell: helm repo add longhorn https://charts.longhorn.io
      tags:
        - on-premise
        - helm

    - name: Add stable helm repository
      shell: helm repo add stable https://charts.helm.sh/stable
      tags:
        - on-premise
        - helm
    
    - name: Update Helm local repository
      shell: helm repo update
      tags:
        - on-premise
        - helm