---
- hosts: masters[0]
  remote_user: "centos"
  tasks:
    - name: Add Longhorn helm repository
      shell: helm repo add longhorn https://charts.longhorn.io
      tags:
        - on-premise
        - helm

    - name: Add metallb helm repository
      shell: helm repo add bitnami https://charts.bitnami.com/bitnami
      tags:
        - on-premise
        - helm

    - name: Add wso2 helm repository
      shell: helm repo add wso2 https://helm.wso2.com
      tags:
        - on-premise
        - helm

    - name: Add Vault helm repository
      shell: helm repo add wso2 https://helm.wso2.com
      tags:
        - on-premise
        - helm

    - name: Add stable helm repository
      shell: helm repo add stable https://charts.helm.sh/stable
      tags:
        - on-premise
        - helm
    
    - name: Update Helm local repository
      shell: helm repo update
      tags:
        - on-premise
        - helm