- hosts: masters[0]
  remote_user: "svc_local_rke"
  vars:
    config_dir: "opt/k8s/config"
  tasks:
    - name: Run rke up to install kubernetes
      shell: "/usr/bin/rke up --config /{{ config_dir }}/rke/cluster.yml"
    - name: Copy configuration from master to local
      fetch:
        src: "/{{ config_dir }}/rke/{{ item }}"
        dest: /tmp/
        flat: yes 
      with_items:
        - cluster.rkestate
        - cluster.yml
        - kube_config_cluster.yml
    - name: Create a symbolic link for kubectl config
      file:
        src: "/{{ config_dir }}/rke/kube_config_cluster.yml"
        dest: /home/svc_local_rke/.kube/config
        owner: svc_local_rke
        group: svc_local_rke
        state: link